### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA_superbuild#39]
* make sure boost version is compatible with cmake 3.12 or newer.
* update Python to latest

other dependencies may stay at their current version if there are no issues

The tarballs for the superbuild are fetched from missmarple.lbl.gov in /var/www/TECA/TECA_deps/ add new tarballs there.

**Comment by elbashandy** [comment]
I have been building the project on docker using the fedora:28, fedora:29 and ubuntu:18.04 images with cmake 3.13 installed. I also updated Python to 2.7.15 in CMakeLists.txt and added the tarball file in our server.

boost is building normally. However, I couldn't fully build some of the libraries till I installed some of the dependancies like:
- pcre to build SWIG.
- expat for udunits.
- zlib-devel for LIBXLSXWRITER
- findutils
- gcc-gfortran

I also had to link xlocale.h to locale.h because numpy wasn't able to build and was giving an error it couldn't find xlocale.h
`ln -s /usr/include/locale.h /usr/include/xlocale.h`

**I had specific issues related to each linux distro.:**

Fedora 29:
- curl's version is looking for openssl-1.1.1

Fedora 28:
- curl's version is looking for openssl-1.1.0 normally but sslv3 has to be enabled. So I had to add `enable-ssl3 enable-ssl3-method` to the `${OPENSSL_SOURCE}/config` command in CMakeLists.txt.

Ubuntu 18:04:
- I had to change ncurses to version 6.1 instead of 6.0 because it was giving a syntax error at building it.


At the end, everything was built successfully except TECA where in both fedora 28 and ubuntu 18:04 (I didn't try fixing the openssl-1.1.1 fedora 29 issue) it was giving these errors:

```
-- Build files have been written to: /root/TECA_superbuild/build/TECA-prefix/src/TECA-build
[ 93%] Performing build step for 'TECA'
Scanning dependencies of target teca_core
[  1%] Building CXX object core/CMakeFiles/teca_core.dir/teca_algorithm_executive.cxx.o
[  1%] Building CXX object core/CMakeFiles/teca_core.dir/teca_binary_stream.cxx.o
[  2%] Building CXX object core/CMakeFiles/teca_core.dir/teca_algorithm.cxx.o
In file included from /root/TECA_superbuild/build/TECA-prefix/src/TECA/core/teca_algorithm.h:8:0,
                 from /root/TECA_superbuild/build/TECA-prefix/src/TECA/core/teca_algorithm.cxx:1:
/root/TECA_superbuild/build/TECA-prefix/src/TECA/core/teca_algorithm_fwd.h:145:28: error: 'function' in namespace 'std' does not name a template type
 bool operator!=(const std::function<T> &lhs, const std::function<T> &rhs)
                            ^~~~~~~~
/root/TECA_superbuild/build/TECA-prefix/src/TECA/core/teca_algorithm_fwd.h:145:36: error: expected ',' or '...' before '<' token
 bool operator!=(const std::function<T> &lhs, const std::function<T> &rhs)
                                    ^
/root/TECA_superbuild/build/TECA-prefix/src/TECA/core/teca_algorithm_fwd.h:145:73: error: 'bool operator!=(int)' must have an argument of class or enumerated type
 bool operator!=(const std::function<T> &lhs, const std::function<T> &rhs)
                                                                         ^
[  3%] Building CXX object core/CMakeFiles/teca_core.dir/teca_calendar.cxx.o
[  3%] Building CXX object core/CMakeFiles/teca_core.dir/teca_dataset.cxx.o
core/CMakeFiles/teca_core.dir/build.make:62: recipe for target 'core/CMakeFiles/teca_core.dir/teca_algorithm.cxx.o' failed
make[5]: *** [core/CMakeFiles/teca_core.dir/teca_algorithm.cxx.o] Error 1
make[5]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:986: recipe for target 'core/CMakeFiles/teca_core.dir/all' failed
make[4]: *** [core/CMakeFiles/teca_core.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/TECA.dir/build.make:121: recipe for target 'TECA-prefix/src/TECA-stamp/TECA-build' failed
make[2]: *** [TECA-prefix/src/TECA-stamp/TECA-build] Error 2
CMakeFiles/Makefile2:81: recipe for target 'CMakeFiles/TECA.dir/all' failed
make[1]: *** [CMakeFiles/TECA.dir/all] Error 2
```

After googling the errors, people are suggesting that the error is that the compiler is not being set to build c++11 code. I tried doing that in CMakeLists.txt by adding these lines but it failed:
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

**Comment by burlen** [comment]
so we have to draw the line somewhere, things like pearl, compilers, and swig are not something we are going to include in the superbuild.

btw, did you update the numpy version as well? If not that would be one thing to do first.

as you found, teca uses c++11, and it's already been enabled, so setting the cmake standard is unnecessary. the resaon we don't use the cmake calls is that teca predates cmake's support for c++11. 

```
error: 'function' in namespace 'std' does not name a template type
```
this is often because a header file has not been included, the relevant header is `functional`. you see this when upgrading stl release because they will clean up unnecessary includes that were hiding the fact that we forgot to include that header.

**Comment by elbashandy** [comment]
The necessary updates to packages are done including Python, numpy & ncurses in #40
