### ISSUE TITLE
superbuild cross-compile for knl fails - illegal instruction

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA_superbuild#48]
Attempting to cross-compile for knl with `-DTARGET_PLATFORM=knl` fails on the ncurses build step.  The ncurses build log shows that it fails due to an illegal instruction error: `./run_tic.sh: line 173: 54897 Illegal instruction     ( $TIC_PATH -x -s -o "$TERMINFO" $source )`.  It appears that other libraries (HDF5) encounter similar problems.

I assume this is because the ncurses build is attempting to run code on the login nodes that contain KNL-specific instructions.

A workaround would be to avoid cross-compiling: compiling on a KNL node directly. This workaround does not work for the case where the install is located in `/global/common/software/`, since that filesystem does not have write access when logged into a node.  That is the use-case I'm currently targeting, unfortunately.

Two potential solutions occur to me:
1. We don't support cross-compiling TECA_superbuild on knl; this would mean that we would have to do a native superbuild build and manually cross-compile TECA for knl (rather than having the superbuild invoke the TECA build)
2. We could change the compiler flags set by the `-DTARGET_PLATFORM=knl` flag, so that they generate instructions for both haswell and for knl.  (Can this be done for GNU compilers?  I know intel can, and I think GNU can, but I'm not immediately seeing how.)

```bash
    cmake \
          -DCMAKE_CXX_COMPILER=`which g++` \
          -DCMAKE_C_COMPILER=`which gcc` \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/global/common/software/m1517/users/taobrien/TECA_superbuild/install_knl_develop \
          -DENABLE_MPICH=OFF \
          -DENABLE_OPENMPI=OFF \
          -DENABLE_CRAY_MPICH=ON \
          -DENABLE_TECA_TEST=OFF \
          -DENABLE_TECA_DATA=OFF \
          -DENABLE_READLINE=OFF \
          -DTARGET_PLATFORM=knl \
          -DENABLE_TECA=ON \
          -DTECA_SOURCE=develop \
          ./TECA_superbuild

```

Any thoughts @burlen?

**Comment by burlen** [comment]
@taobrienlbl The superbuild will not work on KNL. We looked into it at one point and found a number of dependencies cannot be cross compiled - for instance Python. At the time we decided It's not worth the effort. However one can in theory use a compute node to compile directly for KNL. This is also likely not worth the effort since the primary difference between KNL and Haswell instruction set is AVX256(Haswell) vs AVX512(KNL). This brings back how disappointing KNL is compared to the prerelease Hype that we were fed by intel. 

In terms of TECA through profiling I found avx512 instructions don't provide a significant speed up in our C++/Fortran codes. Most of our bottlenecks are not floating point calculations. Im skeptical that it will make any difference in Python codes as well. At most you'd get a 2x speed up in floating point sections of the code by using avx512. In reality vectorization rarely realizes the theoretical maximum because of confounding factors, overheads, etc.

At the time we looked into this I wrote a blog post about cross compileing KNL on confluence at one point. Unfortunately that got lost in the transition away from confluence.

**Comment by taobrienlbl** [comment]
Got it-- that makes sense.  I went ahead and used the haswell-compiled version on KNL, and it ran just fine, consistent with what you are indicating.  And now that you mention it, I do remember that blog post.

I'm okay with closing this and marking it as "won't fix", if you're good with that.

**Comment by burlen** [comment]
sounds good to me
